/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _CLOCK_CONFIG_H_
#define _CLOCK_CONFIG_H_

#include "fsl_common.h"

typedef enum {
    kClockModule_FIRC,
    kClockModule_FXOSC,
    kClockModule_MUX0_CSC_DC,
    kClockModule_MUX1_CSC_DC,
    kClockModule_MUX2_CSC_DC,
    kClockModule_MUX3_CSC_DC,
    kClockModule_MUX4_CSC_DC,
    kClockModule_MUX5_CSC_DC,
    kClockModule_MUX6_CSC_DC,
    kClockModule_MUX7_CSC_DC,
    kClockModule_MUX8_CSC_DC,
    kClockModule_MUX9_CSC_DC,
    kClockModule_MUX10_CSC_DC,
    kClockModule_MUX11_CSC_DC,
    kClockModule_JTAG_TCK,
    kClockModule_PLL,
    kClockModule_RTC,
    kClockModule_SIRC,
    kClockModule_SXOSC,
} clock_module_t;

/*******************************************************************************
 * Definitions
 ******************************************************************************/
#define BOARD_OSC32KNP_CLK_HZ                         32768U  /*!< Board nano-power 32kHz oscillator frequency in Hz */

/*******************************************************************************
 ************************ BOARD_InitBootClocks function ************************
 ******************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes default configuration of clocks.
 *
 */
void BOARD_InitBootClocks(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ********************** Configuration BOARD_BootClockRUN ***********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_BootClockRUN configuration
 ******************************************************************************/


/* Clock outputs (values are in Hz): */
#define BOARD_BOOTCLOCKRUN_AIPS_PLAT_CLK              80000000UL     /* Clock consumers of AIPS_PLAT_CLK output : CRC, EIM, ERM, FLEXCAN_0, FLEXCAN_1, FLEXCAN_2, FLEXCAN_3, FLEXCAN_4, FLEXCAN_5, FLEXIO, INTM, LPSPI_0, LPUART_0, LPUART_1, LPUART_2, LPUART_3, LPUART_4, LPUART_5, LPUART_6, LPUART_7, LPUART_8, MSCM, SEMA42 */
#define BOARD_BOOTCLOCKRUN_AIPS_SLOW_CLK              40000000UL     /* Clock consumers of AIPS_SLOW_CLK output : CMU_0, CMU_1, CMU_2, CMU_3, CMU_4, LPCMP_0, LPCMP_1, LPCMP_2, LPI2C_0, LPI2C_1, LPSPI_1, LPSPI_2, LPSPI_3, LPSPI_4, LPSPI_5, LPUART_10, LPUART_11, LPUART_12, LPUART_13, LPUART_14, LPUART_15, LPUART_9, MCM_0, MU0_B, MU1_B, PIT_0, PIT_1, PIT_2, RTC, SAI_0, SAI_1, SIUL2, TEMPSENSE, TRGMUX, TSPC, WKPU */
#define BOARD_BOOTCLOCKRUN_CLKOUT_RUN                 0UL            /* Clock consumers of CLKOUT_RUN output : N/A */
#define BOARD_BOOTCLOCKRUN_CLKOUT_STANDBY             24000000UL     /* Clock consumers of CLKOUT_STANDBY output : N/A */
#define BOARD_BOOTCLOCKRUN_CORE_CLK                   160000000UL    /* Clock consumers of CORE_CLK output : ADC_0, ADC_1, ADC_2, BCTU, DMAMUX_0, DMAMUX_1, EDMA, ERM, FLEXIO, LCU_0, LCU_1, SysTick, XBIC_AXBS, XBIC_AXBS_EDMA, XBIC_AXBS_PERI, XBIC_AXBS_TCM, XRDC */
#define BOARD_BOOTCLOCKRUN_DCM_CLK                    40000000UL     /* Clock consumers of DCM_CLK output : N/A */
#define BOARD_BOOTCLOCKRUN_EMAC_MII_RMII_TX_CLK       0UL            /* Clock consumers of EMAC_MII_RMII_TX_CLK output : N/A */
#define BOARD_BOOTCLOCKRUN_EMAC_RX_CLK                48000000UL     /* Clock consumers of EMAC_RX_CLK output : N/A */
#define BOARD_BOOTCLOCKRUN_EMAC_TS_CLK                48000000UL     /* Clock consumers of EMAC_TS_CLK output : N/A */
#define BOARD_BOOTCLOCKRUN_EMAC_TX_CLK                48000000UL     /* Clock consumers of EMAC_TX_CLK output : N/A */
#define BOARD_BOOTCLOCKRUN_FIRC_CLK                   48000000UL     /* Clock consumers of FIRC_CLK output : MC_RGM, SIUL2 */
#define BOARD_BOOTCLOCKRUN_FLEXCAN0_PE_CLK            48000000UL     /* Clock consumers of FLEXCAN0_PE_CLK output : FLEXCAN_0 */
#define BOARD_BOOTCLOCKRUN_FLEXCAN1_PE_CLK            48000000UL     /* Clock consumers of FLEXCAN1_PE_CLK output : FLEXCAN_1 */
#define BOARD_BOOTCLOCKRUN_FLEXCAN2_PE_CLK            48000000UL     /* Clock consumers of FLEXCAN2_PE_CLK output : FLEXCAN_2 */
#define BOARD_BOOTCLOCKRUN_FLEXCAN3_PE_CLK            48000000UL     /* Clock consumers of FLEXCAN3_PE_CLK output : FLEXCAN_3 */
#define BOARD_BOOTCLOCKRUN_FLEXCAN4_PE_CLK            48000000UL     /* Clock consumers of FLEXCAN4_PE_CLK output : FLEXCAN_4 */
#define BOARD_BOOTCLOCKRUN_FLEXCAN5_PE_CLK            48000000UL     /* Clock consumers of FLEXCAN5_PE_CLK output : FLEXCAN_5 */
#define BOARD_BOOTCLOCKRUN_FXOSC_CLK                  16000000UL     /* Clock consumers of FXOSC_CLK output : SAI_0, SAI_1 */
#define BOARD_BOOTCLOCKRUN_HSE_CLK                    80000000UL     /* Clock consumers of HSE_CLK output : N/A */
#define BOARD_BOOTCLOCKRUN_LBIST_CLK                  40000000UL     /* Clock consumers of LBIST_CLK output : N/A */
#define BOARD_BOOTCLOCKRUN_PLL_PHI0_CLK               160000000UL    /* Clock consumers of PLL_PHI0_CLK output : N/A */
#define BOARD_BOOTCLOCKRUN_PLL_PHI1_CLK               160000000UL    /* Clock consumers of PLL_PHI1_CLK output : N/A */
#define BOARD_BOOTCLOCKRUN_QSPI_2XSFCK                48000000UL     /* Clock consumers of QSPI_2xSFCK output : N/A */
#define BOARD_BOOTCLOCKRUN_QSPI_MEM_CLK               160000000UL    /* Clock consumers of QSPI_MEM_CLK output : N/A */
#define BOARD_BOOTCLOCKRUN_QSPI_SFCK                  24000000UL     /* Clock consumers of QSPI_SFCK output : N/A */
#define BOARD_BOOTCLOCKRUN_RTC_CLK                    0UL            /* Clock consumers of RTC_CLK output : LPCMP_0, LPCMP_1, LPCMP_2, RTC */
#define BOARD_BOOTCLOCKRUN_SIRC_CLK                   32000UL        /* Clock consumers of SIRC_CLK output : PIT_0 */
#define BOARD_BOOTCLOCKRUN_STM0_CLK                   48000000UL     /* Clock consumers of STM0_CLK output : STM_0, STM_1 */
#define BOARD_BOOTCLOCKRUN_STM1_CLK                   48000000UL     /* Clock consumers of STM1_CLK output : N/A */
#define BOARD_BOOTCLOCKRUN_SXOSC_CLK                  0UL            /* Clock consumers of SXOSC_CLK output : N/A */
#define BOARD_BOOTCLOCKRUN_TCK                        0UL            /* Clock consumers of TCK output : N/A */
#define BOARD_BOOTCLOCKRUN_TRACE_CLK                  48000000UL     /* Clock consumers of TRACE_CLK output : N/A */

/*! @brief Clock pre-initialization function.
 */
extern void BOARD_ClockPreConfig(void);
/*! @brief Clock post-initialization function.
 */
extern void BOARD_ClockPostConfig(void);
/*******************************************************************************
 * API for BOARD_BootClockRUN configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function contains initialization of clocks module.
 *
 */
void BOARD_BootClockRUN_InitClockModule(clock_module_t module);

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_BootClockRUN(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

#endif /* _CLOCK_CONFIG_H_ */

