/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: MCXE31B
package_id: MCXE31BMPB
mcu_data: ksdk2_0
processor_version: 0.2509.30
pin_labels:
- {pin_num: '27', pin_signal: PTE3, label: pin_pte3_config, identifier: pin_pte3_config}
- {pin_num: '26', pin_signal: PTE14, label: dsa, identifier: dsa}
- {pin_num: '49', pin_signal: PTC3, label: ENET_PHY_RST, identifier: ENET_PHY_RST}
- {pin_num: '81', pin_signal: PTC13, label: SAI_0_SYNC, identifier: SAI_0_SYNC}
- {pin_num: '79', pin_signal: PTB2, label: SAI_0_D0_TX, identifier: SAI_0_D0_TX}
- {pin_num: '83', pin_signal: PTC12, label: SAI_0_BCLK, identifier: SAI_0_BCLK}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_siul2.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
    BOARD_InitDEBUG_UARTPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'false'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitDEBUG_UARTPins:
- options: {createDeInit: 'true', callFromInitBoot: 'true', coreID: core0, enableClock: 'false'}
- pin_list:
  - {pin_num: '27', peripheral: LPUART_5, signal: RX, pin_signal: PTE3, identifier: ''}
  - {pin_num: '26', peripheral: LPUART_5, signal: TX, pin_signal: PTE14, identifier: '', direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitDEBUG_UARTPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitDEBUG_UARTPins(void)
{

    /* PTE3 (pin 27) is configured as LPUART_5 RX */
    const siul2_pin_settings_t BOARD_INITDEBUG_UARTPINS_PTE3 =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 131u,
        .mux                         = kPORT_MUX_AS_GPIO,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_DISABLED,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .slewRateCtrlSel             = kPORT_SLEW_RATE_NOT_AVAILABLE,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_ENABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_DISABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .inputMuxReg                 = {
                                         192u
                                       },
        .inputMux                    = {
                                         kPORT_INPUT_MUX_ALT1,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT
                                       },
        .initValue                   = 2u
    };
    SIUL2_PinInit(&BOARD_INITDEBUG_UARTPINS_PTE3);

    /* PTE14 (pin 26) is configured as LPUART_5 TX */
    const siul2_pin_settings_t BOARD_INITDEBUG_UARTPINS_PTE14 =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 142u,
        .mux                         = kPORT_MUX_ALT4,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_NOT_AVAILABLE,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .slewRateCtrlSel             = kPORT_SLEW_RATE_NOT_AVAILABLE,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_DISABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_ENABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .initValue                   = 2u
    };
    SIUL2_PinInit(&BOARD_INITDEBUG_UARTPINS_PTE14);

}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitDEBUG_UARTPins_deinit
 * Description   : This is a de-initialization function for 'BOARD_InitDEBUG_UARTPins' function.
 * It sets all pins features (routing, direction and electrical) to their after-reset state.
 * It also tries to route the previous peripheral signals to their default pins.
 *
 * END ****************************************************************************************************************/
void BOARD_InitDEBUG_UARTPins_deinit(void)
{

    /* PTE3 (pin 27) is disabled */
    const siul2_pin_settings_t BOARD_INITDEBUG_UARTPINS_DEINIT_pin_pte3_config =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 131u,
        .mux                         = kPORT_MUX_AS_GPIO,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_DISABLED,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .slewRateCtrlSel             = kPORT_SLEW_RATE_NOT_AVAILABLE,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_DISABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_DISABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .inputMuxReg                 = {
                                         144u,
                                         158u,
                                         19u,
                                         192u,
                                         350u,
                                         67u
                                       },
        .inputMux                    = {
                                         kPORT_INPUT_MUX_ALT0,
                                         kPORT_INPUT_MUX_ALT0,
                                         kPORT_INPUT_MUX_ALT0,
                                         kPORT_INPUT_MUX_ALT0,
                                         kPORT_INPUT_MUX_ALT0,
                                         kPORT_INPUT_MUX_ALT0,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT
                                       },
        .initValue                   = 2u
    };
    SIUL2_PinInit(&BOARD_INITDEBUG_UARTPINS_DEINIT_pin_pte3_config);

    /* PTE14 (pin 26) is disabled */
    const siul2_pin_settings_t BOARD_INITDEBUG_UARTPINS_DEINIT_dsa =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 142u,
        .mux                         = kPORT_MUX_AS_GPIO,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_NOT_AVAILABLE,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .slewRateCtrlSel             = kPORT_SLEW_RATE_NOT_AVAILABLE,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_DISABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_DISABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .inputMuxReg                 = {
                                         145u,
                                         159u,
                                         29u,
                                         368u,
                                         4u,
                                         67u
                                       },
        .inputMux                    = {
                                         kPORT_INPUT_MUX_ALT0,
                                         kPORT_INPUT_MUX_ALT0,
                                         kPORT_INPUT_MUX_ALT0,
                                         kPORT_INPUT_MUX_ALT0,
                                         kPORT_INPUT_MUX_ALT0,
                                         kPORT_INPUT_MUX_ALT0,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT
                                       },
        .initValue                   = 2u
    };
    SIUL2_PinInit(&BOARD_INITDEBUG_UARTPINS_DEINIT_dsa);

}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitFlexCANPins:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'false'}
- pin_list:
  - {pin_num: '100', peripheral: FLEXCAN_0, signal: TX, pin_signal: PTA7}
  - {pin_num: '102', peripheral: FLEXCAN_0, signal: RX, pin_signal: PTA6}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitFlexCANPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitFlexCANPins(void)
{

    /* PTA7 (pin 100) is configured as FLEXCAN_0 TX */
    const siul2_pin_settings_t BOARD_INITFLEXCANPINS_PTA7 =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 7u,
        .mux                         = kPORT_MUX_ALT4,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_DISABLED,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .slewRateCtrlSel             = kPORT_SLEW_RATE_NOT_AVAILABLE,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_DISABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_ENABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .initValue                   = 2u
    };
    SIUL2_PinInit(&BOARD_INITFLEXCANPINS_PTA7);

    /* PTA6 (pin 102) is configured as FLEXCAN_0 RX */
    const siul2_pin_settings_t BOARD_INITFLEXCANPINS_PTA6 =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 6u,
        .mux                         = kPORT_MUX_AS_GPIO,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_NOT_AVAILABLE,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .slewRateCtrlSel             = kPORT_SLEW_RATE_NOT_AVAILABLE,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_ENABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_DISABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .inputMuxReg                 = {
                                         0u
                                       },
        .inputMux                    = {
                                         kPORT_INPUT_MUX_ALT2,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT
                                       },
        .initValue                   = 2u
    };
    SIUL2_PinInit(&BOARD_INITFLEXCANPINS_PTA6);
    
    
    
    /* PTA11 (pin 98) is configured as FLEXCAN_1 TX */
    const siul2_pin_settings_t BOARD_INITFLEXCANPINS_PTA11 =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 11,
        .mux                         = kPORT_MUX_ALT1,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_DISABLED,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .slewRateCtrlSel             = kPORT_SLEW_RATE_NOT_AVAILABLE,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_DISABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_ENABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .initValue                   = 2u
    };
    SIUL2_PinInit(&BOARD_INITFLEXCANPINS_PTA11);


    /* PTA12 (pin 96) is configured as FLEXCAN_1 RX */
    const siul2_pin_settings_t BOARD_INITFLEXCANPINS_PTA12 =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 12,
        .mux                         = kPORT_MUX_AS_GPIO,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_NOT_AVAILABLE,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .slewRateCtrlSel             = kPORT_SLEW_RATE_NOT_AVAILABLE,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_ENABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_DISABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .inputMuxReg                 = {
                                         513-512
                                       },
        .inputMux                    = {
                                         kPORT_INPUT_MUX_ALT2,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT
                                       },
        .initValue                   = 2u
    };
    SIUL2_PinInit(&BOARD_INITFLEXCANPINS_PTA12);
    
    
    
    
    /* PTE24 (pin XX) is configured as FLEXCAN_2 TX */
    const siul2_pin_settings_t BOARD_INITFLEXCANPINS_PTE24 =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 152,
        .mux                         = kPORT_MUX_ALT3,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_DISABLED,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .slewRateCtrlSel             = kPORT_SLEW_RATE_NOT_AVAILABLE,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_DISABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_ENABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .initValue                   = 2u
    };
    SIUL2_PinInit(&BOARD_INITFLEXCANPINS_PTE24);


    /* PTE25 (pin XX) is configured as FLEXCAN_2 RX */
    const siul2_pin_settings_t BOARD_INITFLEXCANPINS_PTE25 =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 153,
        .mux                         = kPORT_MUX_AS_GPIO,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_NOT_AVAILABLE,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .slewRateCtrlSel             = kPORT_SLEW_RATE_NOT_AVAILABLE,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_ENABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_DISABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .inputMuxReg                 = {
                                         514-512
                                       },
        .inputMux                    = {
                                         kPORT_INPUT_MUX_ALT3,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT
                                       },
        .initValue                   = 2u
    };
    SIUL2_PinInit(&BOARD_INITFLEXCANPINS_PTE25);
    
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitMIKROEUARTPins:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'false'}
- pin_list:
  - {pin_num: 'XX', peripheral: LPUART_2, signal: TX, pin_signal: PTE12, direction: OUTPUT}
  - {pin_num: 'XX', peripheral: LPUART_2, signal: RX, pin_signal: PTD17}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitMIKROEUARTPins
 * Description   : LPUART2 MIKROE connector pins.
 *                 PTE12 (TX-MIKROE), PTD17 (RX-MIKROE [4])
 *                 TODO: Fill in correct mux/IMCR values from the reference manual.
 *
 * END ****************************************************************************************************************/
void BOARD_InitMIKROEUARTPins(void)
{
    /* PTE12 is configured as LPUART_2 TX */
    /* TODO: set .mux to the correct ALT for LPUART2_TX on PTE12 */
    const siul2_pin_settings_t BOARD_INITMIKROEUARTPINS_PTE12 =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 140u,                              /* PTE12: 128 + 12 */
        .mux                         = kPORT_MUX_ALT3,                   /* TODO: verify ALT */
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_NOT_AVAILABLE,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .slewRateCtrlSel             = kPORT_SLEW_RATE_NOT_AVAILABLE,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_DISABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_ENABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .initValue                   = 2u
    };
    SIUL2_PinInit(&BOARD_INITMIKROEUARTPINS_PTE12);

    /* PTD17 is configured as LPUART_2 RX */
    /* TODO: set .inputMuxReg and .inputMux to the correct IMCR index/ALT for LPUART2_RX on PTD17 */
    const siul2_pin_settings_t BOARD_INITMIKROEUARTPINS_PTD17 =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 113u,                              /* PTD17: 96 + 17 */
        .mux                         = kPORT_MUX_AS_GPIO,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_NOT_AVAILABLE,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .slewRateCtrlSel             = kPORT_SLEW_RATE_NOT_AVAILABLE,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_ENABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_DISABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .inputMuxReg                 = {
                                         701-512
                                       },
        .inputMux                    = {
                                         kPORT_INPUT_MUX_ALT2,           /* TODO: verify ALT */
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT
                                       },
        .initValue                   = 2u
    };
    SIUL2_PinInit(&BOARD_INITMIKROEUARTPINS_PTD17);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitEMACPins:
- options: {callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '48', peripheral: EMAC, signal: MII_RMII_MDIO, pin_signal: PTB4, direction: INPUT/OUTPUT}
  - {pin_num: '47', peripheral: EMAC, signal: MII_RMII_MDC, pin_signal: PTB5}
  - {pin_num: '50', peripheral: EMAC, signal: MII_RMII_TXD0, pin_signal: PTC2, slewRate: slowestSetting}
  - {pin_num: '51', peripheral: EMAC, signal: MII_RMII_TXD1, pin_signal: PTD7, slewRate: slowestSetting}
  - {pin_num: '54', peripheral: EMAC, signal: MII_RMII_TX_EN, pin_signal: PTD12, slewRate: slowestSetting}
  - {pin_num: '65', peripheral: EMAC, signal: MII_RMII_RX_DV, pin_signal: PTC17}
  - {pin_num: '61', peripheral: EMAC, signal: MII_RMII_RXD0, pin_signal: PTC1}
  - {pin_num: '62', peripheral: EMAC, signal: MII_RMII_RXD1, pin_signal: PTC0}
  - {pin_num: '49', peripheral: SIUL2, signal: 'GPIO, 67', pin_signal: PTC3, direction: INPUT/OUTPUT, initValue: state_1, slewRate: slowestSetting}
  - {pin_num: '55', peripheral: EMAC, signal: MII_RMII_TX_CLK, pin_signal: PTD11, safeMode: outputOff, slewRate: slowestSetting}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitEMACPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitEMACPins(void)
{

    /* PTB4 (pin 48) is configured as EMAC MII_RMII_MDIO */
    const siul2_pin_settings_t BOARD_INITEMACPINS_PTB4 =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 36u,
        .mux                         = kPORT_MUX_ALT5,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_DISABLED,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .slewRateCtrlSel             = kPORT_SLEW_RATE_NOT_AVAILABLE,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_ENABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_ENABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .inputMuxReg                 = {
                                         291u
                                       },
        .inputMux                    = {
                                         kPORT_INPUT_MUX_ALT1,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT
                                       },
        .initValue                   = 2u
    };
    SIUL2_PinInit(&BOARD_INITEMACPINS_PTB4);

    /* PTB5 (pin 47) is configured as EMAC MII_RMII_MDC */
    const siul2_pin_settings_t BOARD_INITEMACPINS_PTB5 =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 37u,
        .mux                         = kPORT_MUX_ALT7,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_DISABLED,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .slewRateCtrlSel             = kPORT_SLEW_RATE_NOT_AVAILABLE,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_DISABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_ENABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .initValue                   = 2u
    };
    SIUL2_PinInit(&BOARD_INITEMACPINS_PTB5);

    /* PTC2 (pin 50) is configured as EMAC MII_RMII_TXD0 */
    const siul2_pin_settings_t BOARD_INITEMACPINS_PTC2 =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 66u,
        .mux                         = kPORT_MUX_ALT5,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_DISABLED,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .slewRateCtrlSel             = kPORT_SLEW_RATE_SLOWEST,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_DISABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_ENABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .initValue                   = 2u
    };
    SIUL2_PinInit(&BOARD_INITEMACPINS_PTC2);

    /* PTD7 (pin 51) is configured as EMAC MII_RMII_TXD1 */
    const siul2_pin_settings_t BOARD_INITEMACPINS_PTD7 =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 103u,
        .mux                         = kPORT_MUX_ALT5,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_DISABLED,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .slewRateCtrlSel             = kPORT_SLEW_RATE_SLOWEST,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_DISABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_ENABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .initValue                   = 2u
    };
    SIUL2_PinInit(&BOARD_INITEMACPINS_PTD7);

    /* PTD12 (pin 54) is configured as EMAC MII_RMII_TX_EN */
    const siul2_pin_settings_t BOARD_INITEMACPINS_PTD12 =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 108u,
        .mux                         = kPORT_MUX_ALT5,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_DISABLED,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .slewRateCtrlSel             = kPORT_SLEW_RATE_SLOWEST,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_DISABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_ENABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .initValue                   = 2u
    };
    SIUL2_PinInit(&BOARD_INITEMACPINS_PTD12);

    /* PTC17 (pin 65) is configured as EMAC MII_RMII_RX_DV */
    const siul2_pin_settings_t BOARD_INITEMACPINS_PTC17 =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 81u,
        .mux                         = kPORT_MUX_AS_GPIO,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_DISABLED,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .slewRateCtrlSel             = kPORT_SLEW_RATE_NOT_AVAILABLE,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_ENABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_DISABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .inputMuxReg                 = {
                                         292u
                                       },
        .inputMux                    = {
                                         kPORT_INPUT_MUX_ALT1,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT
                                       },
        .initValue                   = 2u
    };
    SIUL2_PinInit(&BOARD_INITEMACPINS_PTC17);

    /* PTC1 (pin 61) is configured as EMAC MII_RMII_RXD0 */
    const siul2_pin_settings_t BOARD_INITEMACPINS_PTC1 =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 65u,
        .mux                         = kPORT_MUX_AS_GPIO,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_DISABLED,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .slewRateCtrlSel             = kPORT_SLEW_RATE_NOT_AVAILABLE,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_ENABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_DISABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .inputMuxReg                 = {
                                         294u
                                       },
        .inputMux                    = {
                                         kPORT_INPUT_MUX_ALT1,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT
                                       },
        .initValue                   = 2u
    };
    SIUL2_PinInit(&BOARD_INITEMACPINS_PTC1);

    /* PTC0 (pin 62) is configured as EMAC MII_RMII_RXD1 */
    const siul2_pin_settings_t BOARD_INITEMACPINS_PTC0 =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 64u,
        .mux                         = kPORT_MUX_AS_GPIO,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_DISABLED,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .slewRateCtrlSel             = kPORT_SLEW_RATE_NOT_AVAILABLE,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_ENABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_DISABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .inputMuxReg                 = {
                                         295u
                                       },
        .inputMux                    = {
                                         kPORT_INPUT_MUX_ALT1,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT
                                       },
        .initValue                   = 2u
    };
    SIUL2_PinInit(&BOARD_INITEMACPINS_PTC0);

    /* PTC3 (pin 49) is configured as SIUL2 GPIO, 67 */
    const siul2_pin_settings_t BOARD_INITEMACPINS_ENET_PHY_RST =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 67u,
        .mux                         = kPORT_MUX_AS_GPIO,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_DISABLED,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .slewRateCtrlSel             = kPORT_SLEW_RATE_SLOWEST,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_ENABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_ENABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .inputMux                    = {
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT
                                       },
        .initValue                   = 1u
    };
    SIUL2_PinInit(&BOARD_INITEMACPINS_ENET_PHY_RST);

    /* PTD11 (pin 55) is configured as EMAC MII_RMII_TX_CLK */
    const siul2_pin_settings_t BOARD_INITEMACPINS_PTD11 =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 107u,
        .mux                         = kPORT_MUX_AS_GPIO,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_DISABLED,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .slewRateCtrlSel             = kPORT_SLEW_RATE_SLOWEST,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_ENABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_DISABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .inputMuxReg                 = {
                                         296u
                                       },
        .inputMux                    = {
                                         kPORT_INPUT_MUX_ALT1,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT
                                       },
        .initValue                   = 2u
    };
    SIUL2_PinInit(&BOARD_INITEMACPINS_PTD11);

}
