/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void);

/*! @name PTE3 (number 27), pin_pte3_config
  @{ */

/* Defined symbols */
#define BOARD_INITDEBUG_UARTPINS_DEINIT_pin_pte3_config_PORT PTE                 /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_DEINIT_pin_pte3_config_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_DEINIT_pin_pte3_config_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                                                 /* @} */

/*! @name PTE14 (number 26)
  @{ */

/* Defined symbols */
#define BOARD_INITDEBUG_UARTPINS_DEINIT_dsa_PORT PTE                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_DEINIT_dsa_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_DEINIT_dsa_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                                      /* @} */

/*!
 * @brief This is a de-initialization function for 'BOARD_InitDEBUG_UARTPins' function.
 * It sets all pins features (routing, direction and electrical) to their after-reset state.
 * It also tries to route the previous peripheral signals to their default pins.
 *
 */
void BOARD_InitDEBUG_UARTPins_deinit(void);
/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitFlexCANPins(void);

/*! @name PTC3 (number 49), ENET_PHY_RST
  @{ */

/* Symbols to be used with SIUL2 driver */
#define BOARD_INITEMACPINS_ENET_PHY_RST_SIUL2_BASE SIUL2         /*!<@brief SIUL2 peripheral base pointer */
#define BOARD_INITEMACPINS_ENET_PHY_RST_GPIO kSIUL2_PTC          /*!<@brief GPIO peripheral port */
#define BOARD_INITEMACPINS_ENET_PHY_RST_GPIO_PIN_MASK (1U << 67U) /*!<@brief GPIO pin mask */

/* Defined symbols */
#define BOARD_INITEMACPINS_ENET_PHY_RST_PORT PTC                 /*!<@brief PORT peripheral base pointer */
#define BOARD_INITEMACPINS_ENET_PHY_RST_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITEMACPINS_ENET_PHY_RST_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*!
 * @brief LPUART2 MIKROE connector pins (PTE12=TX, PTD17=RX).
 *        TODO: fill in correct mux/IMCR values before use.
 */
void BOARD_InitMIKROEUARTPins(void);

/*!
 * @brief LPUART0/LPUART3 RS485 smoke-test pins.
 *
 */
void BOARD_InitRS485UARTPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitEMACPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
