/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef MCUXSDK_VERSION_H_
#define MCUXSDK_VERSION_H_

#define MCUXSDK_VERSION_YEAR      2025
#define MCUXSDK_VERSION_MAJOR     12
#define MCUXSDK_VERSION_MINOR     0


#define MCUXSDK_VERSION_NUM       (MCUXSDK_VERSION_YEAR * 10000 + MCUXSDK_VERSION_MAJOR * 100 + MCUXSDK_VERSION_MINOR)
#define MCUXSDK_VERSION_FULL_STR  "2025.12.00"

#endif /* MCUXSDK_VERSION_H_ */
